# Generated by Django 4.2.3 on 2024-09-03 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('originalurl', models.CharField(blank=True, max_length=100, null=True)),
                ('shorturl', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
